### ISSUE TITLE
logo not loading

### ISSUE THREAD

**Issue by liddafire** [sierrataylor/safety-equipment-inspection-app#103]
this is on the bb/frontend branch. 
alright, so when you load the page, in the header where the logo should appear, the iconic "there's an image but it hasn't loaded" image appears instead. At the moment I'm not sure how to rectify it. I'm assuming that it's something to do with the path to the logo, or it could be that it's a transparent background? IF you happen to have an idea lmk. the image is in the images folder within the view folder for header.

**Comment by liddafire** [comment]
issue 
"Failed to load resource: the server responded with a status of 404 (Not Found)"

**Comment by carriecuva** [comment]
This has been fixed. It is currently showing up by moving the images folder into the assets folder and updating the src file path accordingly!
