### ISSUE TITLE
Start connecting controllers to database

### ISSUE THREAD

**Issue by sierrataylor** [sierrataylor/safety-equipment-inspection-app#19]
Backend devs need to start connecting the FireStore db to the API. I have already wrote some skeleton code for them.

**Comment by sierrataylor** [comment]
Started working on this today
Will close this issue once I have connected controllers for all tables to the db

**Comment by jgurary** [comment]
Might as well assign yourself and make this more specific: what's the minimum work you need to do to call the controllers "connected"? Is this a "minimum" as in "the database talks to the controller" or "we can read/write real data"?

**Comment by sierrataylor** [comment]
I have to add read/write functionality to the backend. So I need to add
HTTP methods like GET/POST etc to the controllers.

**Comment by sierrataylor** [comment]
Started. Will need more work later.
