### ISSUE TITLE
Create Mockup Database Schema 

### ISSUE THREAD

**Issue by carriecuva** [sierrataylor/safety-equipment-inspection-app#2]
Utilizing Lucid Chart, build and design the database structure that will be used for the project

**Comment by sierrataylor** [comment]
Do you think you'll add the database schema as part of our documentation when you are done with the it?

**Comment by carriecuva** [comment]
Yes! I was planning on uploading it along with a word doc specifying with descriptions today after the meeting if there is a field we don’t have that Mrs. Gurary wants to put in the database.

**Comment by sierrataylor** [comment]
Just remember to make your own branch. Nothing can be pushed to main
without a pull request.

**Comment by carriecuva** [comment]
just added branch and made pull request!
