### ISSUE TITLE
Dashboard View Page

### ISSUE THREAD

**Issue by rboland01** [sierrataylor/safety-equipment-inspection-app#26]
Create web page for dashboard

**Comment by rboland01** [comment]
Bobby can work on these, but wanted to add the other front end dev since this will start to begin the html and css work
--will need to look into angular/ts more too

**Comment by liddafire** [comment]
for now, focus on the inspector view, and manager view. the admin view is still very rough (tho I will add the base today anyways since I don't want to wait for info any longer), and there's a lot of questions I still have
