### ISSUE TITLE
Revamp Web Component Structure

### ISSUE THREAD

**Issue by rboland01** [sierrataylor/safety-equipment-inspection-app#28]
Currently, the web structure is set up with the 3 or 4 example angular components given on start up (Home, Counter, Fetch-Data). 

Need to create more component pages and revamp how the web pages will be structured. We will need the first web page to be the log-in, followed by the dashboard, then future web page components.

(not sure how much this will need back end changing too, but assuming it might)

**Comment by jgurary** [comment]
Too broad, if you have a component or page in mind that someone should make, open an issue for it specifically.

**Comment by rboland01** [comment]
Good Point.  By this I mean change what page gets opened on start up, and delete old example web files in order to first send the user to the log-in page, then to the dashboard

**Comment by liddafire** [comment]
[for how to set a default page](https://stackoverflow.com/questions/1125280/setting-the-default-page-for-asp-net-visual-studio-server-configuration), tho I don't know if this means for users this is also the case. 
for going to the dashboard page next, shouldn't the log-in button be connected to go to that page?

**Comment by liddafire** [comment]
button to link to dashboard

[in typscript](https://stackoverflow.com/questions/63401478/how-do-i-implement-clickable-link-button-that-opens-a-webpage-in-another-tab-in)

[in html](https://stackoverflow.com/questions/2906582/how-do-i-create-an-html-button-that-acts-like-a-link)
