### ISSUE TITLE
Mock Up V2

### ISSUE THREAD

**Issue by liddafire** [sierrataylor/safety-equipment-inspection-app#33]
All the questions from mockup 1 need to be addressed. be completed by next Friday

**Comment by jgurary** [comment]
Weak issue, there isn't even a link to the resource here. Guess it's this: https://github.com/sierrataylor/safety-equipment-inspection-app/tree/main/SafetyEquipmentInspection/SafetyEquipmentInspectionApp/docs 

Seems like a discussion that could use more comments and iteration, suggest you move the discussion to Notion and/or Figma to make it easier to collaborate, but also consider moving ahead with an mvp using the v1 design and iterating on it as you discover new problems/features.

**Comment by liddafire** [comment]
already on it (b^_^)b

was mainly using this as a placeholder, discussions have gone on over texts

**Comment by liddafire** [comment]
scratching out page 5 of mockup 1, dashboard should start with different pages to select even for the inspector, not just a list of past scans

**Comment by liddafire** [comment]
complete
