### ISSUE TITLE
QR Page

### ISSUE THREAD

**Issue by carriecuva** [sierrataylor/safety-equipment-inspection-app#62]
structure the QR code page

**Comment by jgurary** [comment]
Seems closed?

**Comment by carriecuva** [comment]
updated the layout of the QR scanner page. There is now a button in the top left to go back to the dashboard page. The image for the qr scanner is now centered. Also, there is now an enter equipment id input along with a submit button. Right now, there is an alert when you click the submit button if the input is empty. If there is text, it goes to the inspection form page.

**Comment by carriecuva** [comment]
I am going to close this issue since the layout is updated and the qr scanner actually works!
