### ISSUE TITLE
Add code that allows for a QR code to be generated

### ISSUE THREAD

**Issue by carriecuva** [sierrataylor/safety-equipment-inspection-app#63]
look into qr code generator and add it to project

**Comment by jgurary** [comment]
Vague issue, but seems closed by a recent PR. Tag issues in the description of the PR and they can close automatically, e.g. Closes "#whatevernumber"

**Comment by carriecuva** [comment]
this will get started hopefully this coming week once it is decided if there will be an angular component specifically for generating a QR code

**Comment by carriecuva** [comment]
the angular component has been created! Going to add code from github to see if it functions properly.

**Comment by carriecuva** [comment]
Currently began to add the code for the qr generator. The functionality is not 100% yet, but that will be my goal for this coming week. I added elements to the HTML file along with adding two ts files into the qr-generator folder and two js files into the assets folder. These files are named qrcodegen-input-demo.js & qrcodegen.js

**Comment by carriecuva** [comment]
Using different code now to get it to work: hopefully, we have a functional Qr generator soon.
