### ISSUE TITLE
add web-based qr reader

### ISSUE THREAD

**Issue by liddafire** [sierrataylor/safety-equipment-inspection-app#7]
either the library and then create the code, or steal last group's code

**Comment by liddafire** [comment]
after the current backend branch is pushed into main, the library that I have that reads QR codes needs to be added

**Comment by liddafire** [comment]
once in, push it to main, and back to a branch so I can add the script for a page to do the reading

**Comment by liddafire** [comment]
added the code that can be done before merging the front-end and qr-base together

**Comment by liddafire** [comment]
library has been added woo

**Comment by carriecuva** [comment]
update: added the javascript code needed to get it to work! Getting some build errors now saying there are duplicate attributes that I need to fix then it should work

**Comment by carriecuva** [comment]
qr reader code is all in the branch cc/qrscanner. Now it is a matter of deciding if it should be merged now or wait until we know for sure it works on mobile

**Comment by liddafire** [comment]
dope!

**Comment by jgurary** [comment]
Has anyone validated it actually reads QR codes?

**Comment by carriecuva** [comment]
I am working on validating it reads QR codes; right now it does not. Currently, the scanner has its own Angular component and the code is added to my branch. It is a matter of figuring out why the JavaScript is not working as it should on the page.
